# Generated by Django 5.1.6 on 2025-02-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='factore_year',
            new_name='factory_year',
        ),
    ]
