# Generated by Django 5.1.6 on 2025-02-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_factore_year_car_factory_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/% y/% m/% d/'),
        ),
    ]
