# Generated by Django 5.1.6 on 2025-02-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_brand_alter_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/%y/%m/%d/'),
        ),
    ]
